"""PDF report generator for Esper — converts markdown content to styled PDFs.

Uses fpdf2 (lightweight, no system-level dependencies like Cairo/Pango).
Falls back gracefully if fpdf2 is not installed.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from typing import Any

try:
    from fpdf import FPDF  # type: ignore[import-untyped]

    _HAS_FPDF = True
except ImportError:
    _HAS_FPDF = False


# ------------------------------------------------------------------ #
# Colour palette
# ------------------------------------------------------------------ #

_SEVERITY_COLOURS: dict[str, tuple[int, int, int]] = {
    "Critical": (220, 38, 38),
    "High": (234, 88, 12),
    "Medium": (202, 138, 4),
    "Low": (22, 163, 74),
    "Info": (59, 130, 246),
    "Unknown": (107, 114, 128),
}

_HEADER_BG = (30, 41, 59)
_HEADER_FG = (255, 255, 255)
_SECTION_BG = (241, 245, 249)


# ------------------------------------------------------------------ #
# Report PDF class (only defined when fpdf2 is available)
# ------------------------------------------------------------------ #

if _HAS_FPDF:

    class EsperReportPDF(FPDF):  # type: ignore[misc]
        """Styled PDF subclass for Esper security reports."""

        def __init__(self) -> None:
            super().__init__()
            self.set_auto_page_break(auto=True, margin=20)

        # Page header
        def header(self) -> None:
            if self.page_no() == 1:
                return  # First page has custom header
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, "Esper Security Assessment", align="L")
            self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        # Page footer
        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f"Generated by Esper - {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", align="C")

        # -- Section helpers --

        def add_title_page(self, target_url: str, score: int, confidence: float, scan_date: str) -> None:
            """Render the cover / title page."""
            self.add_page()

            # Background bar
            self.set_fill_color(*_HEADER_BG)
            self.rect(0, 0, 210, 90, style="F")

            # Title
            self.set_y(25)
            self.set_font("Helvetica", "B", 28)
            self.set_text_color(*_HEADER_FG)
            self.cell(0, 14, "Esper Security Assessment", align="C", new_x="LMARGIN", new_y="NEXT")

            self.ln(4)
            self.set_font("Helvetica", "", 12)
            self.cell(0, 8, scan_date, align="C", new_x="LMARGIN", new_y="NEXT")

            # Target & Score
            self.set_y(100)
            self.set_text_color(30, 30, 30)
            self.set_font("Helvetica", "B", 14)
            self.cell(0, 10, "Target", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 11)
            self.cell(0, 8, target_url, new_x="LMARGIN", new_y="NEXT")

            self.ln(6)
            self.set_font("Helvetica", "B", 14)
            self.cell(0, 10, "Security Score", new_x="LMARGIN", new_y="NEXT")

            # Score badge
            badge_colour = _score_colour(score)
            self.set_fill_color(*badge_colour)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 36)
            self.cell(40, 22, f"{score}", fill=True, align="C")
            self.set_text_color(30, 30, 30)
            self.set_font("Helvetica", "", 11)
            self.cell(0, 22, f"  / 100    (Confidence: {confidence:.0%})", new_x="LMARGIN", new_y="NEXT")

        def add_section(self, title: str, level: int = 1) -> None:
            """Add a section heading."""
            self.ln(4)
            size = 14 if level == 1 else 12
            self.set_font("Helvetica", "B", size)
            self.set_text_color(30, 41, 59)
            self.set_fill_color(*_SECTION_BG)
            self.cell(0, 8, title, ln=True, fill=True)
            self.ln(2)
            self.set_text_color(30, 30, 30)

        def _avail_w(self) -> float:
            """Return available width inside current margins."""
            return self.w - self.l_margin - self.r_margin

        def add_text(self, text: str) -> None:
            """Add a paragraph of plain text, stripping markdown bold/italic."""
            clean = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
            clean = re.sub(r"\*(.+?)\*", r"\1", clean)
            clean = clean.replace("`", "")
            self.set_font("Helvetica", "", 10)
            self.multi_cell(self._avail_w(), 5, clean)
            self.ln(1)

        def add_bullet(self, text: str) -> None:
            """Add a bullet-point line."""
            clean = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
            clean = re.sub(r"\*(.+?)\*", r"\1", clean)
            for emoji in ("\u274c ", "\u2705 ", "\U0001f534 ", "\U0001f7e0 ", "\U0001f7e1 ", "\U0001f7e2 ", "\u26aa "):
                clean = clean.replace(emoji, "")
            clean = clean.replace("`", "")
            self.set_font("Helvetica", "", 9)
            self.cell(6, 5, chr(8226))
            self.multi_cell(self._avail_w() - 6, 5, clean)

        def add_severity_finding(self, severity: str, title: str, category: str = "") -> None:
            """Add a finding with a coloured severity badge."""
            colour = _SEVERITY_COLOURS.get(severity, _SEVERITY_COLOURS["Unknown"])

            # Badge
            self.set_fill_color(*colour)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 8)
            badge_w = self.get_string_width(f" {severity} ") + 4
            self.cell(badge_w, 5, f" {severity} ", fill=True)

            # Title
            self.set_text_color(30, 30, 30)
            self.set_font("Helvetica", "B", 9)
            self.cell(0, 5, f"  {title}", new_x="LMARGIN", new_y="NEXT")

            if category:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(100, 100, 100)
                self.cell(0, 4, f"    {category}", new_x="LMARGIN", new_y="NEXT")
            self.ln(1)

        def add_table(self, headers: list[str], rows: list[list[str]]) -> None:
            """Add a simple bordered table."""
            col_count = len(headers)
            col_w = 190 // col_count

            # Header row
            self.set_font("Helvetica", "B", 9)
            self.set_fill_color(241, 245, 249)
            for h in headers:
                self.cell(col_w, 7, h, border=1, fill=True, align="C")
            self.ln()

            # Data rows
            self.set_font("Helvetica", "", 9)
            for row in rows:
                for cell_text in row:
                    self.cell(col_w, 6, str(cell_text)[:50], border=1, align="L")
                self.ln()


# ------------------------------------------------------------------ #
# Public API
# ------------------------------------------------------------------ #


def generate_pdf_report(
    target_url: str,
    markdown_content: str,
    security_score: int,
    confidence: float,
    findings: list[dict[str, Any]] | None = None,
    output_dir: str | None = None,
) -> str | None:
    """Generate a PDF report from Esper scan data.

    Returns the path to the generated PDF, or ``None`` if fpdf2 is not installed.
    """
    if not _HAS_FPDF:
        return None

    pdf = EsperReportPDF()

    # Title page
    scan_date = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    pdf.add_title_page(target_url, security_score, confidence, scan_date)

    # Executive Summary
    pdf.add_page()
    pdf.add_section("1. Executive Summary")
    score_text = _score_health_label(security_score)
    pdf.add_text(f"The target has a security score of {security_score}/100, indicating {score_text} security posture.")
    pdf.add_text(f"Confidence: {confidence:.0%} - based on scanner data availability.")

    # Findings
    if findings:
        pdf.add_section("2. Security Findings")
        severity_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4, "Unknown": 5}
        sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.get("severity", ""), 5))
        for f in sorted_findings:
            pdf.add_severity_finding(
                f.get("severity", "Unknown"),
                f.get("title", ""),
                f.get("category", ""),
            )
    else:
        pdf.add_section("2. Security Findings")
        pdf.add_text("No findings detected.")

    # Mitigations table
    pdf.add_section("3. Recommended Mitigations")
    mitigation_lines = _extract_mitigations_from_markdown(markdown_content)
    if mitigation_lines:
        pdf.add_table(
            ["Priority", "Action", "Effort", "Risk Reduction"],
            mitigation_lines,
        )
    else:
        pdf.add_text("No mitigations generated.")

    # Raw markdown as appendix (strip emoji that Courier can't render)
    pdf.add_section("4. Full Report (Markdown)")
    pdf.set_font("Courier", "", 7)
    truncated = markdown_content[:8000]
    if len(markdown_content) > 8000:
        truncated += "\n... [truncated] ..."
    safe_md = _strip_emoji(truncated)
    pdf.multi_cell(pdf._avail_w(), 3.5, safe_md)

    # Save
    out_dir = output_dir or os.path.join(os.getcwd(), "reports")
    os.makedirs(out_dir, exist_ok=True)

    from urllib.parse import urlparse
    domain = urlparse(target_url).netloc or "unknown"
    clean = domain.replace(":", "_").replace("/", "_")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = os.path.join(out_dir, f"esper_{clean}_{ts}.pdf")

    pdf.output(filepath)
    return filepath


# ------------------------------------------------------------------ #
# Helpers
# ------------------------------------------------------------------ #

def _score_colour(score: int) -> tuple[int, int, int]:
    if score >= 80:
        return (22, 163, 74)
    if score >= 60:
        return (202, 138, 4)
    if score >= 40:
        return (234, 88, 12)
    return (220, 38, 38)


def _score_health_label(score: int) -> str:
    if score >= 80:
        return "strong"
    if score >= 60:
        return "moderate"
    if score >= 40:
        return "concerning"
    return "critical"


def _strip_emoji(text: str) -> str:
    """Remove emoji and non-Latin1 characters that Courier can't render."""
    import unicodedata
    cleaned: list[str] = []
    for ch in text:
        cp = ord(ch)
        if cp < 256 and ch.isprintable():
            cleaned.append(ch)
        elif cp in (0x0A, 0x0D, 0x09):  # newline / tab
            cleaned.append(ch)
        elif cp < 256:
            cleaned.append(ch)
        else:
            cat = unicodedata.category(ch)
            # Keep only Letters (L*) and Numbers (N*) from BMP, drop everything else
            if cat.startswith(("L", "N")) and cp < 0x10000:
                cleaned.append(ch)
            else:
                cleaned.append("-")
    return "".join(cleaned)


def _extract_mitigations_from_markdown(md: str) -> list[list[str]]:
    """Parse the mitigation table from the markdown report."""
    rows: list[list[str]] = []
    in_section = False
    for line in md.splitlines():
        if "Mitigations" in line and "##" in line:
            in_section = True
            continue
        if in_section and line.startswith("##"):
            break
        if in_section and line.startswith("|") and "---" not in line:
            parts = [p.strip() for p in line.split("|")[1:-1]]
            if len(parts) >= 4 and parts[0] != "Priority":
                rows.append(parts[:4])
    return rows
